server {
    listen 8080;
    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
        add_header Cache-Control no-cache;
    }

    location /static/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
