import type { User } from '@/types/user';
import type { Plan } from './plan';

/**
 * Workspace representation
 */
export interface Workspace {
  /**
   * Workspace id
   */
  id: string;

  /**
   * Workspace name
   */
  name: string;

  /**
   * Workspace description
   */
  description?: string;

  /**
   * Workspace image
   */
  image?: string;

  /**
   * Invite hash of workspace for invite links
   */
  inviteHash: string;

  /**
   * Workspace members array
   */
  team: Member[];

  /**
   * Workspace tariff plan
   */
  plan: Plan;

  /**
   * Date when workspace was charged last time
   */
  lastChargeDate: Date;

  /**
   * ID of subscription if it subscribed
   * Returns from CloudPayments
   */
  subscriptionId?: string;

  /** True if workspace is used for debugging */
  isDebug?: boolean;

  /** True if workspace is blocked */
  isBlocked?: boolean;
}

/**
 * Represents confirmed member info in DB
 */
export interface ConfirmedMember {
  /**
   * Document id
   */
  id: string;

  /**
   * Id of the member of workspace
   */
  user: User;

  /**
   * Is user admin in workspace
   */
  isAdmin: boolean;
}

/**
 * Represents pending member info in DB
 */
export interface PendingMember {
  /**
   * Document id
   */
  id: string;

  /**
   * User email for invitation
   */
  email: string;
}

/**
 * Represents both member types in workspace team
 */
export type Member = ConfirmedMember | PendingMember;

/**
 * Workspace preview with basic public info
 * Contains only basic fields: id, name, image
 * Used for public-facing features like SSO login page
 */
export type WorkspacePreview = Pick<Workspace, 'id' | 'name' | 'image'> | null;

/**
 * SAML attribute mapping configuration
 */
export interface SamlAttributeMapping {
  /**
   * Email attribute name
   */
  email: string;

  /**
   * Name attribute name
   */
  name?: string;
}

/**
 * SAML-specific configuration
 */
export interface SamlConfig {
  /**
   * IdP Entity ID
   */
  idpEntityId: string;

  /**
   * SSO URL
   */
  ssoUrl: string;

  /**
   * X.509 certificate
   */
  x509Cert: string;

  /**
   * NameID format
   */
  nameIdFormat?: string;

  /**
   * Attribute mapping
   */
  attributeMapping: SamlAttributeMapping;
}

/**
 * SSO configuration type (output from API)
 * Contains server-generated fields like 'type'
 */
export interface WorkspaceSsoConfig {
  /**
   * Is SSO enabled
   */
  enabled: boolean;

  /**
   * Is SSO enforced
   */
  enforced: boolean;

  /**
   * SSO provider type (generated by server, not provided by client)
   */
  type: string;

  /**
   * SAML-specific configuration
   */
  saml: SamlConfig;
}

/**
 * SSO configuration input type (input to API)
 * Does not include server-generated fields like 'type'
 * Structure is identical to WorkspaceSsoConfig except for the 'type' field
 */
export interface WorkspaceSsoConfigInput {
  /**
   * Is SSO enabled
   */
  enabled: boolean;

  /**
   * Is SSO enforced
   */
  enforced: boolean;

  /**
   * SAML-specific configuration
   */
  saml: SamlConfig;
}
