name: ESLint CodeX

on: [pull_request]

jobs:
  lint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn lint:js
