name: Build and deploy

on: [push]

env:
  DOCKER_IMAGE_NAME: hawk-garage
  DOCKERHUB_USER: codexteamuser

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo "VUE_APP_API_ENDPOINT=https://api.stage.hawk.so/graphql" > ./.env

      - run: echo "VUE_APP_API_ENDPOINT=https://api.beta.hawk.so/graphql" > ./.env
        if: endsWith(github.ref, '/prod')

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}

      - name: Deploy on stage
        if: endsWith(github.ref, '/stage')
        run: |
          DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"stage\",\"secret_token\":\"$DEPLOY_TOKEN\"}" https://stage.hawk.so/deploy

      - name: Deploy on prod
        if: endsWith(github.ref, '/prod')
        run: |
          DEPLOY_TOKEN_PROD=${{ secrets.DEPLOY_TOKEN_PROD }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"prod\",\"secret_token\":\"$DEPLOY_TOKEN_PROD\"}" https://beta.hawk.so/deploy
