name: Build and deploy

on: [push]

env:
  DOCKER_IMAGE_NAME: hawk-garage

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE_NAME .

      - name: Get branch name
        uses: nelonoel/branch-name@v1

      - name: Push to registry
        if: endsWith(github.ref, '/stage')
        run: |
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.REGISTRY_NAME }}/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker login ${{ secrets.REGISTRY_ADDRESS }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.REGISTRY_NAME }}/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker logout

      - name: Deploy
        if: endsWith(github.ref, '/stage')
        run: |
          DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"stage\",\"secret_token\":\"$DEPLOY_TOKEN\"}" https://stage.hawk.so/deploy
