name: Build and deploy

on: [push]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/hawk-garage


jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo "VUE_APP_API_ENDPOINT=https://api.stage.hawk.so" > ./.env

      - run: echo "VUE_APP_API_ENDPOINT=https://api.beta.hawk.so" > ./.env
        if: endsWith(github.ref, '/prod')

      - run: echo "VUE_APP_CLOUDPAYMENTS_PUBLIC_ID=test_api_00000000000000000000001" >> ./.env

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}

      - name: Deploy on stage
        if: endsWith(github.ref, '/stage')
        run: |
          curl --user ${{ secrets.DEPLOY_HAWK_STAGE_AUTH }} ${{ secrets.DEPLOY_HAWK_STAGE_ADDRESS }}?image=${{ env.DOCKER_REPO }}:stage

      - name: Deploy on prod
        if: endsWith(github.ref, '/prod')
        run: |
          DEPLOY_TOKEN_PROD=${{ secrets.DEPLOY_TOKEN_PROD }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"prod\",\"secret_token\":\"$DEPLOY_TOKEN_PROD\"}" https://beta.hawk.so/deploy
