name: Build and deploy

on: [push]

env:
  DOCKER_IMAGE_NAME: hawk-garage
  DOCKERHUB_USER: codexteamuser

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo "VUE_APP_API_ENDPOINT=https://api.stage.hawk.so/graphql" > ./.env

      - run: echo "VUE_APP_API_ENDPOINT=https://api.beta.hawk.so/graphql" > ./.env
        if: endsWith(github.ref, '/prod')

      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Get branch name
        uses: nelonoel/branch-name@v1

      - name: Push to private registry
        if: endsWith(github.ref, '/stage')
        run: |
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.REGISTRY_NAME }}/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker login ${{ secrets.REGISTRY_ADDRESS }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.REGISTRY_NAME }}/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker logout

      - name: Push to Docker Hub
        if: endsWith(github.ref, '/prod')
        run: |
          docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker login -u $DOCKERHUB_USER -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKERHUB_USER/$DOCKER_IMAGE_NAME:$BRANCH_NAME
          docker logout

      - name: Deploy on stage
        if: endsWith(github.ref, '/stage')
        run: |
          DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"stage\",\"secret_token\":\"$DEPLOY_TOKEN\"}" https://stage.hawk.so/deploy

      - name: Deploy on prod
        if: endsWith(github.ref, '/prod')
        run: |
          DEPLOY_TOKEN_PROD=${{ secrets.DEPLOY_TOKEN_PROD }}
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"prod\",\"secret_token\":\"$DEPLOY_TOKEN_PROD\"}" http://beta.hawk.so:7102/deploy
